### ISSUE TITLE
Compliance Error

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#1]
**Issue:** Redirect to payments module after clicking in case number.
-Confirmation is needed for compliance after clicking submit button and not closing the page.
-Provide description for compliance remarks.
-more_vert button is not working.
**Module:** Compliance

**Actual Result:**
Failed, User should know where to view or click in compliance details.

![nineten](https://user-images.githubusercontent.com/34052250/54406525-6bcd1b00-4715-11e9-86a8-d416298a1d9f.PNG)
![twenty](https://user-images.githubusercontent.com/34052250/54404584-fc542d00-470e-11e9-8e40-611f91ff86e4.PNG)

**Comment by fqui8** [comment]
**- Deployment version: 0.1.16** 
**- File Path: fda-client-portal/src/components/Compliance.vue**

**- Resolution:**
- [ ]  view button has been added to prevent clicking the entire list
- [ ] confirmation has been added
