### ISSUE TITLE
View License Application Error

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#10]
**Issue**: Created By and Product line formated by ID.
-Tin not formatted in masking and Address is undefined.
**Module:** View License Application

**Expected Result:**
Can view Application data details

![bbbbbbbbbbbbbb](https://user-images.githubusercontent.com/34052250/54416727-2e7b8400-473b-11e9-8e8e-5b4e2d756cd2.PNG)
![eeeeeewee](https://user-images.githubusercontent.com/34052250/54416729-2e7b8400-473b-11e9-9d64-b91df447ce35.PNG)
![eleven](https://user-images.githubusercontent.com/34052250/54416730-2f141a80-473b-11e9-96c7-f8987d67f5a4.PNG)
![yyyyyyyryr](https://user-images.githubusercontent.com/34052250/54416742-376c5580-473b-11e9-8ac0-0fd89853db8c.PNG)

**Comment by VPBelo** [comment]
**Issue:** Tin is not formatted in masking.
Credentials:
Username: Vince
Password: Vince123

  - Actual result
![ViewApplication](https://user-images.githubusercontent.com/34052250/55135810-adbf7d80-5167-11e9-8172-ad4c0c50fee9.PNG)

**Comment by abalita** [comment]
Closing this issue. New application overview is already implemented.
