### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#11]
- Expected Result
- [ ] Approver's uploaded avatar will display
- can upload approver's avatar

- Actual Result
- [ ] Failed. Avatar displayed is random
- [ ] Failed. no option to upload avatar

- Remarks
- [ ] uploading of avatar should be included in the My Profile page 

![Screen Shot 2019-03-18 at 11 30 35 AM](https://user-images.githubusercontent.com/36065227/54505165-adf29880-4971-11e9-9bac-81c80b1aad60.png)

**Comment by fqui8** [comment]
Expected Result:
- can save photos as avatar

Actual Result:
- cannot save photos

**Comment by mquijom** [comment]
Deployment Version: **0.1.24**

Modified File(s):
- **fda-client-portal/api/UserAPI.js**
- **fda-client-portal/layout/UserLayout.js**
- **fda-client-portal/plugins/mixins.js**
- **fda-client-portal/views/app/Profile.vue**

Resolutions:
Fixed. Only User Accounts available to modify

![image](https://user-images.githubusercontent.com/34019450/55066412-b73ddc80-50b8-11e9-8c02-8275d9c65525.png)

**Comment by VPBelo** [comment]
- Closing this issue.
  - Actual Result

![profileNew](https://user-images.githubusercontent.com/34052250/55130322-65975f80-5155-11e9-83d2-5fd3ca2e372e.PNG)

**Comment by VPBelo** [comment]
**Issue:** Unable to change Profile Picture. When the page is reloaded ,the same default image appears.

![profileNew](https://user-images.githubusercontent.com/34052250/55141013-5f64ab80-5174-11e9-904b-5a67a15805af.PNG)

**Comment by mquijom** [comment]
Deployment Version: **0.1.25**

Resolution:
Deployment for **0.1.24** didn't reflected to prod

**Comment by mquijom** [comment]
![image](https://user-images.githubusercontent.com/34019450/55199172-16543c00-51f4-11e9-8bba-ca9e95a8a2d7.png)

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![profileclient](https://user-images.githubusercontent.com/34052250/55202733-a2219480-5203-11e9-9af0-6acba4b57ae4.PNG)
![profileclient2](https://user-images.githubusercontent.com/34052250/55202734-a2219480-5203-11e9-87dd-1e047414843d.PNG)
