### ISSUE TITLE
Compliance without attached files

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-client-portal#12]
**Scene: Response without attached files**

- Expected Result
Submitted successfully

- Actual Result 
Didn't submit and got an error

- **Error**
`{ "name":"MongoError","message":"The argument to $each in $push must be an array but it was of type: null","operationTime":"6669604033344307202","ok":0,"errmsg":"The argument to $each in $push must be an array but it was of type: null","code":2,"codeName":"BadValue","$clusterTime":{"clusterTime":"6669604033344307202","signature":{"hash":"F2vSxnbm0eRFzJ+oO5cOyIoIEM8=","keyId":"6625324677164171266"}}}`

**Comment by mquijom** [comment]
Deployment Version: **0.1.20**

Files: 
- **fda-services-lto/case_router.js**

Remarks:
Fixed by adding condition if **attached files** is **not null**

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![Compliance2](https://user-images.githubusercontent.com/34052250/55130828-56b1ac80-5157-11e9-9ee6-19873685d22e.PNG)
