### ISSUE TITLE
Credit Card Form

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-client-portal#13]
**Scene: Payment thru credit card**

Missing options of **Province** and **City/Town**

![image](https://user-images.githubusercontent.com/34019450/54649427-2463d780-4ae5-11e9-9d36-4161193e8b42.png)

**Comment by godofuri76** [comment]
For Testing in v0.1.23
Resolution:
- get data of region, province & city
- validation notification on cvc & submit button

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result
![payments](https://user-images.githubusercontent.com/34052250/55056283-bbf69680-50a0-11e9-8162-a044d6dc3485.PNG)
