### ISSUE TITLE
New License INVALID DATE

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#14]
- Scenario
- [ ] Created/Applied new license

-  Expected Result
- [ ] can create and submit

- Actual
- [ ] Success, but date is null
![Screen Shot 2019-03-22 at 9 20 07 AM](https://user-images.githubusercontent.com/36065227/54795374-f1f1e000-4c86-11e9-8cfa-c515e93ee16e.png)

**Comment by mquijom** [comment]
Deployment Version: **0.1.25**

Modified Files: 
- **fda-services-lto/api/models/LicenseModel.js**

Resolution:
Fixed by setting `date_created` in pre save.

![image](https://user-images.githubusercontent.com/34019450/55149077-714e4a80-5184-11e9-87a4-006a322f7da6.png)

**Comment by VPBelo** [comment]
**Issue:**  Created by in Summary display the old username.
 - Actual Result
![invaliddate](https://user-images.githubusercontent.com/34052250/55457514-b529cf80-561c-11e9-892a-af7659856d9f.PNG)

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![invaliddate2](https://user-images.githubusercontent.com/34052250/55458048-6a10bc00-561e-11e9-9088-f2cdaa424399.PNG)
