### ISSUE TITLE
UI- Portal version

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#15]
Expected Result:
will display version in page footer

Actual Result:
failed

Remarks:
must display version

**Comment by fqui8** [comment]
![Screen Shot 2019-03-24 at 7 22 50 PM](https://user-images.githubusercontent.com/36065227/54878629-3be6eb80-4e6a-11e9-862a-e8e853ba55d5.png)

- For deployment v.1.21
- File path: 
- [ ] fda-client-portal/src/layout/MainLayout.vue

- Resolution:
- [ ] added {{app version}} in the main layout page
- created a method 
`app_version() {`
      `return process.env.VUE_APP_VERSION;`

**Comment by kyango** [comment]
closed
