### ISSUE TITLE
Payment Table

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#17]
Scenario:
- tried to open an unpaid application and will pay thru cc or ecpay. Application is opened from payments table. 
![Screen Shot 2019-03-27 at 9 24 45 AM](https://user-images.githubusercontent.com/36065227/55044874-e16eaa80-5076-11e9-9d01-bc26ac30ba4d.png)

![Screen Shot 2019-03-27 at 9 29 41 AM](https://user-images.githubusercontent.com/36065227/55043900-2e508200-5073-11e9-8aa0-e3979cd48877.png)

Expected Result:
- can display unpaid cases 
- can display pending transaction
- can display payment summary
- can pay thru cc or ecpay

Actual:
- not yet tested for paid transaction if it will appear in the payments table. 
- successfully displayed pending transaction in dialog
- successfully displayed payment summary in dialog. But amount incorrect
- cannot proceed payment thru cc if theres an error, dialog will be closed and cannot proceed.

Remarks:
- 2 dialogs open. pending and payment summary, or pending and cc details. 
![Screen Shot 2019-03-27 at 9 24 19 AM](https://user-images.githubusercontent.com/36065227/55044752-83da5e00-5076-11e9-8e26-36d0819de218.png)
![Screen Shot 2019-03-27 at 9 24 23 AM](https://user-images.githubusercontent.com/36065227/55044753-8472f480-5076-11e9-8d2c-4eb394b8e5d7.png)

**Comment by fqui8** [comment]
Fixed the issue of 2 dialogs open. pending and payment summary, or pending and cc details.

Remarks:
- [ ] must only display UNPAID cases

**Comment by fqui8** [comment]
Fixed. For testing v0.1.26
File path: fda-client-portal/src/views/app/payment/Payment.vue
Resolution:
- [ ] displayed only unpaid cases

**Comment by VPBelo** [comment]
Closing this issue.
Credentials:
Username: Vince
Password: Vince123

  - Actual Result

![payments3](https://user-images.githubusercontent.com/34052250/55462918-7e5ab600-562a-11e9-9f46-1abf026502b7.PNG)
