### ISSUE TITLE
Help button in every step  Client Portal

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#19]
Expected Result:
-  can provide help, guidelines, instructions for every step
![Screen Shot 2019-03-28 at 5 43 10 PM](https://user-images.githubusercontent.com/36065227/55148503-4adbdf80-5183-11e9-9957-98572dba8d06.png)

Actual Result:
- no function yet

Remarks:
- [ ] help is an important function especially in applying license. FDA has special instructions and guidelines (i.e uploading files, etc)

![Screen Shot 2019-03-28 at 5 58 36 PM](https://user-images.githubusercontent.com/36065227/55148495-46afc200-5183-11e9-8884-7408320157ca.png)
![Screen Shot 2019-03-28 at 5 58 23 PM](https://user-images.githubusercontent.com/36065227/55148496-46afc200-5183-11e9-862b-fa8a583db48e.png)
![Screen Shot 2019-03-28 at 5 58 00 PM](https://user-images.githubusercontent.com/36065227/55148497-47485880-5183-11e9-9d44-f9f65a877dde.png)

Question:
- [ ] any suggestions on how to make this work. Do we have to create a dialog for every help buttons?

**Comment by fqui8** [comment]
Fixed. For testing v0.1.26
File path: fda-client-portal/src/views/app/licenses/Create.vue
Resolution: Temporarily add help/instructions in tooltip. 
Remarks: Can modify for future enhancements

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![tooltip1](https://user-images.githubusercontent.com/34052250/55453233-a851af80-560d-11e9-9064-edb683f68c7c.PNG)
![tooltip2](https://user-images.githubusercontent.com/34052250/55453234-a8ea4600-560d-11e9-843d-677554466136.PNG)
![tooltip3](https://user-images.githubusercontent.com/34052250/55453235-a8ea4600-560d-11e9-966f-ada0400c1711.PNG)
![tooltip4](https://user-images.githubusercontent.com/34052250/55453237-a8ea4600-560d-11e9-9bb1-38751f010a03.PNG)
![tooltip5](https://user-images.githubusercontent.com/34052250/55453238-a982dc80-560d-11e9-9d21-8c9b2b011dd0.PNG)
