### ISSUE TITLE
Payment for VARIATION, COMPLIANCE, APPLY NEW LICENSE and RENEWAL LICENSE not working (error: Fee is null)

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#2]
**Issue:** Confirmation is needed for payment if successful or not paid and not closing after clicking next button no idea/action how to proceed in next step.
-No comma for amount of Total.
-ECPAY button is not working.
**Module:** Payment

![four](https://user-images.githubusercontent.com/34052250/54405589-1f341080-4712-11e9-94bb-04bd12ee9ac6.PNG)
![seven](https://user-images.githubusercontent.com/34052250/54405590-1f341080-4712-11e9-8a33-c98bde7b14cc.PNG)
![thirten](https://user-images.githubusercontent.com/34052250/54405591-1f341080-4712-11e9-80a1-a64f4579131f.PNG)

**Comment by godofuri76** [comment]
For Testing in v0.1.23
File Path: app/licenses/view
Resolution: 
- passing of data from temporary access to application overview as well to full access 
- change application overview inside of payment to pending/paid transaction 
- add success & failed notification on credit payment  
- payment summary is working just it didn't have data all data yet
- formats data id

**Comment by VPBelo** [comment]
Issue: Working in Credit Card field but i cannot proceed to next step.
 - Actual Result

![payment](https://user-images.githubusercontent.com/34052250/55055765-07a84080-509f-11e9-8c93-280903d5d79e.PNG)
![payment2](https://user-images.githubusercontent.com/34052250/55055767-0840d700-509f-11e9-9e6e-d8e569eeecda.PNG)
![payment3](https://user-images.githubusercontent.com/34052250/55055769-0840d700-509f-11e9-8c87-d9fed6ec1621.PNG)

**Comment by mquijom** [comment]
Deployment Version: **0.1.25**

Modified File(s):
- **fda-client-portal/views/app/payment/CreditCardPayment.vue**
- **fda-client-portal/plugins/mixins.js**

Resolutions:
Fixed. 

![image](https://user-images.githubusercontent.com/34019450/55136485-7b168480-5169-11e9-80de-22f7d741b823.png)

![image](https://user-images.githubusercontent.com/34019450/55136549-a8fbc900-5169-11e9-9a7d-ce255d84b350.png)

![image](https://user-images.githubusercontent.com/34019450/55136588-cd57a580-5169-11e9-849c-b097e93f6aa9.png)

**Comment by VPBelo** [comment]
**Issue**: View License Application didn't display Summary payments details. 

**Credentials:**
Username: Chz
Password: Chz123

![ClientsView](https://user-images.githubusercontent.com/34052250/55209198-516a6580-521c-11e9-9895-42e9563e518b.PNG)


- For CVC Field its working now for invalid/valid CVC.
  - Actual Result

![creditcard](https://user-images.githubusercontent.com/34052250/55210045-8d072e80-5220-11e9-89ba-d362448c47c8.PNG)

**Comment by VPBelo** [comment]
Closing this issue.
