### ISSUE TITLE
Error in Login after Changing Password

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-client-portal#20]
**Scene: Change Password then Login**

Remarks:
Got this error when logging in after changing password. But when I refresh the browser, the login module works fine again. 
In Console Log: End point extended with path `/secured/accounts` which is wrong.

`Failed to load https://fda-services.herokuapp.com/v1.0/secured/accounts/public/accounts/auth: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://fda-client-portal.herokuapp.com' is therefore not allowed access. The response had HTTP status code 503.`

![image](https://user-images.githubusercontent.com/34019450/55208599-b4a6c880-5219-11e9-9294-0a096d2f546d.png)

**Comment by mquijom** [comment]
Deployment Version: **0.1.26**

Modified File(s): 
- **fda-client-portal/api/CaseAPI.js**
- **fda-client-portal/api/LicenseApi.js**
- **fda-client-portal/api/PasswordAPI.js**
- **fda-client-portal/api/PaymentApi.js**
- **fda-client-portal/api/PlacesApi.js**
- **fda-client-portal/api/ProductApi.js**
- **fda-client-portal/api/RegistrationAPI.js**
- **fda-client-portal/api/TaskApi.js**
- **fda-client-portal/api/UserAPI.js**

Resolutions:
Fixed by setting axios `baseUrl` to `process.env.VUE_APP_API_BASE_URI`

**Comment by VPBelo** [comment]
Closing this issue.
Credentials:
Username: Vince
Password: Vince123

  - Actual Result

![Reset](https://user-images.githubusercontent.com/34052250/55458651-27e87a00-5620-11e9-8941-68eefdbe775c.PNG)
