### ISSUE TITLE
Minor - Error in console "Cannot read property fee of null." but still working in browser.

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#21]
**Error:** Cannot read property fee of null.
  - Actual Result.

![error5](https://user-images.githubusercontent.com/34052250/55210390-09e6d800-5222-11e9-8d95-c7a1875cbf46.PNG)

**Comment by fqui8** [comment]
Issue not applicable. New UI has been implemented.
Closing this issue.
