### ISSUE TITLE
Minor - Output Documents Blank

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#24]
**Issue:** Documents files upload empty files.
  - Actual Result

![o](https://user-images.githubusercontent.com/34052250/55219137-12014080-523f-11e9-9b7e-ace549f2f867.PNG)

**Comment by kyango** [comment]
Issue resolved
![image](https://user-images.githubusercontent.com/34019477/55454195-84906880-5611-11e9-8297-e9106e9f740b.png)

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![Upload](https://user-images.githubusercontent.com/34052250/55462620-c3cab380-5629-11e9-959b-0bef86936a04.PNG)
