### ISSUE TITLE
Minor - New License Application didn't display

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#25]
Issue: New License Application didn't display Summary payments details.
  - Actual Result

![ClientsView](https://user-images.githubusercontent.com/34052250/55219479-f5193d00-523f-11e9-9fb5-4527c62427a0.PNG)

**Comment by mquijom** [comment]
Deployment Version: **0.1.26**

Modified File(s):
- **fda-client-portal/views/apps/licenses/create/tabs/index.js**
- **fda-client-portal/views/apps/licenses/appoverview/tabs/index.js**
- **fda-client-portal/views/registration/tabs/index.js**

Resolutions:
change `module.exports` into `exports default`

**Comment by VPBelo** [comment]
Closing this issue.
Credentials:
Username: Vince
Password: Vince123

  - Actual Result

![ViewApplication2](https://user-images.githubusercontent.com/34052250/55459454-30da4b00-5622-11e9-8971-133c2dabe4a5.PNG)
