### ISSUE TITLE
Minor- Update edit profile stock on the page

### ISSUE THREAD

**Issue by kyango** [centralizedinc/fda-client-portal#29]
Issue: 
After edit and save changes the page is stock on edit profile user content

Expected result:
After saving the new profile (first name and last name) user be able to navigate the app on the sidebar etc.

![image](https://user-images.githubusercontent.com/34019477/55299051-b237af00-5463-11e9-96f1-89d73a7bdfa4.png)

**Comment by mquijom** [comment]
Hi. Please comment below the account used in this test case

**Comment by abalita** [comment]
Closing this issue. Can no longer replicate the error.
