### ISSUE TITLE
Inputting in Credit card details error

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#3]
**Issue:** No confirmation or prompted message for payment if successful or not paid and not closing after clicking submit.
-CVC field has no limit in three digits.
**Module:** Payment

![five](https://user-images.githubusercontent.com/34052250/54406082-b9488880-4713-11e9-801d-bd0d25baebf3.PNG)
![six](https://user-images.githubusercontent.com/34052250/54406083-b9e11f00-4713-11e9-811e-badc44687489.PNG)

**Comment by godofuri76** [comment]
For Testing in v0.1.16
