### ISSUE TITLE
MAJOR- Client Portal PAYMENT/PAYMENT STATUS

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#31]
**Scenario 1: make credit card payment (from license table> selected a case> app overview> payment**
**Result:**
          - successfully paid transaction thru credit card. In license table, payment status does not update. Status still UNPAID
          - select the case again, payment status in app overview is "UNPAID"
          - tried to pay via credit card for the 2nd time, payment successful again. but case still has unpaid status.
**Remarks**:
           - cannot do another payment transaction for the same case
           - no official receipt received in email
           - cannot download official receipt from payment window page
**Console errors**:
- TypeError: Cannot read property 'total' of null,
- TypeError: Cannot read property 'fee' of null

**Scenario 2 Payment from payments table > selected a case > pending transaction dialog > pay now**
**Result:**
           - cannot proceed to payment
**Console errors:** TypeError: Cannot read property 'total' of null
 
**Scenario 3: make payment for another case. from license table> selected case no.> app overview> payment**     
**Result:**
          - [ ] cannot proceed. button doesn't work
**console errors:**: TypeError: Cannot read property 'total' of null

**Scenario 4: created a new license and proceed to payment**
**REsult**
          - [ ] Other test card numbers doesnt work
AMEX, Diners Club, processor specific card like Dankort (PBS) | test card number 76009244561 and VISA 4222222222222
         - [ ] payment successful but status is UNPAID 
![Screen Shot 2019-04-01 at 11 52 16 AM](https://user-images.githubusercontent.com/36065227/55302652-adc7c200-5474-11e9-8c97-34c9143c22c4.png)

**OTHER ISSUES**
- payment summary appeared upon login.
![Screen Shot 2019-04-01 at 10 52 35 AM](https://user-images.githubusercontent.com/36065227/55300870-56255880-546c-11e9-9695-bcbb18e08940.png)
-ECPAY- i created a dialog for ecpay transaction, we can use it to give instruction to clients on what to do when ecpay is selected. rename download filename from "file" to "order of payment". 

**ENHANCEMENT: (already included in issue #35)**
- color for consistency
- disable submit button to avoid double clicking
- ecpay dialog (to give instructions to clients)
- back to main button not working

**Comment by mquijom** [comment]
Resolutions:
For **Scenario 4**, Card number now accepts **13 - 16 length**.

Remarks
The exact amount will be credited if the mode of payment is Credit Card Payment
Kindly comment below the account and case used in the scenario.
When I tried the case in the attached image, the status turns into `PAID`

![image](https://user-images.githubusercontent.com/34019450/55465733-566e5100-5630-11e9-8c30-8d21d6c3d384.png)

**Comment by mquijom** [comment]
Relating this issue to #46

**Comment by fqui8** [comment]
This issue is not applicable to the new UI layout. Closing this issue now
