### ISSUE TITLE
RENEWAL of License 

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#33]
**Scenario 1**- renew license
**Result**
- successfully submitted
- payment summary> payment breakdown is invalid. values are 0
![Screen Shot 2019-04-01 at 12 08 22 PM](https://user-images.githubusercontent.com/36065227/55303116-ef596c80-5476-11e9-8287-d55da963b931.png)
**Console error**
- TypeError: Cannot read property 'current_task' of undefined

**Other issues**
- After printing, current task is empty.
![Screen Shot 2019-04-01 at 12 32 17 PM](https://user-images.githubusercontent.com/36065227/55303702-41e85800-547a-11e9-981e-373a82beb5e5.png)

**Remarks/ Questions/**
- instead of empty current task after case is approved and printed,  what would be the task description? (i.e., for claiming, for release, )
- can send email if license is successfully REnewed
- what if client renew the license before due date, what would be the active license displayed in the dashboard and license page?
![Screen Shot 2019-04-01 at 12 39 41 PM](https://user-images.githubusercontent.com/36065227/55303940-9cce7f00-547b-11e9-9538-4794f4a6cdff.png)

**Enhancements** (already included in issue #35 
- App overviews displays the old username. instead of the updated username
![Screen Shot 2019-04-01 at 12 32 17 PM](https://user-images.githubusercontent.com/36065227/55303827-0306d200-547b-11e9-8fa0-aa6a3ccb999d.png)
- typo error
![Screen Shot 2019-04-01 at 12 10 14 PM](https://user-images.githubusercontent.com/36065227/55303835-15810b80-547b-11e9-8e6a-5e3aaa5884b7.png)

**Comment by abalita** [comment]
closing this issue. New renewal process is already implemented.
