### ISSUE TITLE
MAJOR- VARIATION of License

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#34]
**Scenario 1**- choose variation from license page, fill up details,
**Result**
- cannot submit license
- cannot proceed

**Remarks**
- old values does not display

**Console errors**
vue.runtime.esm.js:1887 TypeError: Cannot read property 'split' of undefined

**Enhancement** (already included in issue #35)
UI
![Screen Shot 2019-04-01 at 12 52 58 PM](https://user-images.githubusercontent.com/36065227/55305508-5e3cc280-5483-11e9-8109-038bef50ecb3.png)

**Comment by mquijom** [comment]
Deployment Version: **0.1.28**

Modified File(s):
- **fda-client-portal/src/views/app/licenses/variations/variations.json**

Resolutions:
change fields `first_name`, `last_name` and `middle_name` to `firstname`, `lastname`, `middlename`

**Comment by VPBelo** [comment]
Closing this issue.
Credentials:
Username: Chz
Password: Chz123

  - Actual Result

![VariationNew](https://user-images.githubusercontent.com/34052250/55471765-0f3a8d00-563d-11e9-946f-b2a50c277ead.PNG)

**Comment by fqui8** [comment]
Reopen issue. same error.
-cannot proceed to variate if client choose all variation (minor and major)

- **scenario 1**
when submitting variation, **(Inclusion of product (finished or raw material) and/or product line)** console error below. dialog doesnt close.
![Screen Shot 2019-04-16 at 12 43 39 PM](https://user-images.githubusercontent.com/36065227/56182555-4d747b00-6045-11e9-8054-85a0d8540232.png)

case submitted but no successful notification. applicant will not be aware that the case has been successfully submitted
![Screen Shot 2019-04-16 at 12 48 40 PM](https://user-images.githubusercontent.com/36065227/56182723-089d1400-6046-11e9-9e46-0772f7a5497b.png)

can save but doesn't close
![Screen Shot 2019-04-16 at 12 40 39 PM](https://user-images.githubusercontent.com/36065227/56182480-07b7b280-6045-11e9-8037-3cbad2683df0.png)

- **scenario 2**
variate again, case cannot be submitted. now it doesn't appear in the license table
![Screen Shot 2019-04-16 at 12 43 39 PM](https://user-images.githubusercontent.com/36065227/56182756-266a7900-6046-11e9-9839-185110fcd617.png)

**-scenario 3**
variate again. same as scenario 1 **(Inclusion of product (finished or raw material) and/or product line)**. successfully submitted but no notification and doesn't close dialog
![Screen Shot 2019-04-16 at 1 02 09 PM](https://user-images.githubusercontent.com/36065227/56183166-de4c5600-6047-11e9-97d7-025e9899b3f3.png)

- **scenario 4**
**Change in business name/address of the source.**
while typing to change business name, console error: TypeError: Cannot read property 'address' of undefined
cannot submit. 
![Screen Shot 2019-04-16 at 1 05 16 PM](https://user-images.githubusercontent.com/36065227/56183256-59ae0780-6048-11e9-9531-c3cadbeda4a1.png)

- **scenario 5**
**Change of key personnel for Quality Assurance, Quality Control, Production Manager, Authorized Person and Pharmacist**
dialog doesnt close, but can save, so client has to click the cancel button to close the dialog
![Screen Shot 2019-04-16 at 1 09 08 PM](https://user-images.githubusercontent.com/36065227/56183370-db059a00-6048-11e9-8de2-1a33eb044d6e.png)

variation successfully submitted.  For payment, same error it doesnt close if payment successfully submitted
![Screen Shot 2019-04-16 at 1 12 45 PM](https://user-images.githubusercontent.com/36065227/56183496-65e69480-6049-11e9-89a1-ad693a3ac52d.png)
![Screen Shot 2019-04-16 at 1 13 06 PM](https://user-images.githubusercontent.com/36065227/56183502-68e18500-6049-11e9-85c6-73ec180d4f96.png)

- **scenario 6**
Transfer of location of the establishment
no data
![Untitled](https://user-images.githubusercontent.com/36065227/56257762-f8e20600-60ff-11e9-8c55-b237e4708626.png)


**Question:
If client variate (example add product line) and submitted the variation application, can he variate again? same field or different field?**

**Comment by abalita** [comment]
Closing issue.
New Variation module implemented.
