### ISSUE TITLE
Minor- ECPay Payment

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#36]
related to issue #31 

Question:
- Is it order of payment or reference number that has to be downloaded for the ECPay transaction?
- order of payment is for FDAC/Bank, im not sure if ECPay/Bayad Centers can accept order of payment. 
- Reference number is similar to DFA's ePayment wherein users download their reference number and pay at any ecPay suthorized partners
![received_10155666151409150](https://user-images.githubusercontent.com/36065227/55312473-386de880-5498-11e9-9a44-eaed59b8b41f.png)

**Comment by abalita** [comment]
Closing this issue. 
EC pay integration is not yet available. 
The current behavior is just for mock-up purposes only.
