### ISSUE TITLE
MAJOR - Variation Payment 

### ISSUE THREAD

**Issue by godofuri76** [centralizedinc/fda-client-portal#38]
Missing: Variation  payment
 
no data to show

**Comment by mquijom** [comment]
Remarks
Some of the applications didn't show the payment summary because of this issue #46 

![image](https://user-images.githubusercontent.com/34019450/55538842-e922f480-56f1-11e9-9d84-6f0ef5326939.png)

**Comment by abalita** [comment]
Closing this issue. May not be applicable to the new variation module
