### ISSUE TITLE
Email confirmation for New License Application/Registration

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#4]
**Issue**: No confirmation or prompted message if the new license is completed or done.
-name of user display as object.
**Module**: New License

**Expected Result:**
Can email confirmation
Can confirm by clicking the button or link in email
**Actual Result:**
Failed, link is in localhost. need to run client portal in localhost to confirm

![One](https://user-images.githubusercontent.com/34052250/54412064-557e8980-472c-11e9-9658-a9ac620d5ba1.PNG)

**Comment by kyango** [comment]
![image](https://user-images.githubusercontent.com/34019477/54975384-de6dae80-4fd1-11e9-8637-4dff1851be96.png)

**Comment by kyango** [comment]
this issue has been fixed and for testing

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![emailConfirm](https://user-images.githubusercontent.com/34052250/55130715-d0956600-5156-11e9-95a6-f31b6b2d2921.PNG)
![emailConfirm2](https://user-images.githubusercontent.com/34052250/55130716-d12dfc80-5156-11e9-81ce-46349d46a259.PNG)
