### ISSUE TITLE
Minor - Application Overview file uploaded

### ISSUE THREAD

**Issue by kyango** [centralizedinc/fda-client-portal#40]
Issue:
No data displayed on application overview (Summary) for uploaded files and output documents
fda-client-portal/components/ApplicationOverview

Expected result:
User can view the file that been uploaded while searching for the summary of the application

![image](https://user-images.githubusercontent.com/34019477/55454811-d6d28900-5613-11e9-9eee-3100536b3be3.png)

**Comment by mquijom** [comment]
Deployment Version: **0.1.29**

Modified File(s):
- **fda-client-portal/app/licenses/appoverview/tabs/Files.vue**

Resolution
Display the uploaded files.

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result


![UploadFiles](https://user-images.githubusercontent.com/34052250/55708667-0bca4b80-5a19-11e9-8ead-d53fb7185d7d.PNG)
