### ISSUE TITLE
Minor - Created by in Summary payments details didn't display updated username its show old username.

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#41]
**Issue:** Created by in Summary payments details didn't display updated username its show old username.

Credentials:
Username: Vince
Password: Vince123#
Case Number: l20190304000092

  - Actual Result

![invaliddate](https://user-images.githubusercontent.com/34052250/55458398-734e5880-561f-11e9-83ba-653146be16aa.PNG)

**Comment by mquijom** [comment]
Deployment Version: **0.1.29**

Modified File(s):
- **fda-client-portal/src/views/app/licenses/appoverview/tabs/AppHistory.vue**
- **fda-client-portal/src/views/app/licenses/appoverview/tabs/AppSummary.vue**

Resolution:
Remove `Created By` in design because it is not necessary.

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![DateSubmitted](https://user-images.githubusercontent.com/34052250/55527625-78b5ac80-56cc-11e9-873e-641c5c938a26.PNG)
