### ISSUE TITLE
Minor- Active License doesnt display new license

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#42]
Scenario: License Renewed

Expected Result:
- ACTIVE LICENSE will display the new one

Actual Result:
- failed to display new license in the ACTIVE LICENSE

**Comment by mquijom** [comment]
Deployment Version: **0.1.29**

Modified File(s):
- **fda-services-lto/api/routes/license_router.js**
- **fda-services-lto/api/dao/LicenseDao.js**

Resolutions
Sort license descending to get the latest.

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![Activelicense](https://user-images.githubusercontent.com/34052250/55530182-9d635180-56d7-11e9-8b66-1bde245780f4.PNG)
![Activelicense1](https://user-images.githubusercontent.com/34052250/55530183-9d635180-56d7-11e9-9d5e-402eaef65fd0.PNG)
