### ISSUE TITLE
Major - RENEWAL, PRINT, VARIATION and VIEW FULL LICENSE button should be not displayed for no active license

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#43]
**Issue:** RENEWAL, PRINT, VARIATION and VIEW FULL LICENSE button should be not displayed for no active license.

Credentials:
Username: Vince
Password: Vince123

  - Actual Result

![NoActivelicense](https://user-images.githubusercontent.com/34052250/55466838-96363800-5632-11e9-9f78-3fb44e766880.PNG)

**Comment by mquijom** [comment]
Deployment Version: **0.1.29**

Modified File(s):
- **fda-client-portal/src/components/ActiveLicense.vue**

Resolution:
Create a `No Active License` sign if there is no active license.

![image](https://user-images.githubusercontent.com/34019450/55468774-b10aab80-5636-11e9-973b-c393b2d7649b.png)

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![variationNoActive](https://user-images.githubusercontent.com/34052250/55527569-33917a80-56cc-11e9-85d8-8b294ec5e363.PNG)
