### ISSUE TITLE
MAJOR - Additional Activities are not saved in the DB

### ISSUE THREAD

**Issue by abalita** [centralizedinc/fda-client-portal#44]
Additional activities are not saved in the DB

**Comment by abalita** [comment]
- Fixed. For testing v0.1.29
 - Modified file(s): fda-services-lto/api/models/LicenseModel.js

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![additionalNew](https://user-images.githubusercontent.com/34052250/55708457-8f376d00-5a18-11e9-811e-b195031a6154.PNG)
