### ISSUE TITLE
Client Account with limited access doesnt show recent activity

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#45]
![Screen Shot 2019-04-04 at 9 32 39 AM](https://user-images.githubusercontent.com/36065227/55523673-caeed180-56bc-11e9-84bd-63b830a8f05b.png)

Scenario: Cashier approved case

Expected Result:
- will display in recent activity

Actual Result:
- failed to show

**Comment by mquijom** [comment]
Hi. Please comment below the account used in this test case. Thanks

**Comment by fqui8** [comment]
Tested in v. 0.1.41. Issue has been fixed.
