### ISSUE TITLE
MAJOR- Payment Credit Card (in Variation)

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#47]
related to issue #39, #31 

**scenario 1:** 
- applied variation > fill up > payment > credit card > submit > loading (failed to submit) > cancel > payment status unpaid

expected result:
- will cancel payment. payment status still unpaid

actual result:
- cc payment did not go through but still trying to submit.
- submit button still loading for trying to submit

**scenario 2:**
- tried to apply another variation (2nd variation) > fill up > payment > credit card > submit > loading (failed to submit again) > cancel > payment status unpaid

expected:
- will cancel payment. payment status still unpaid

actual:
- failed to re-initialize. previous details from previous transaction remain
- still trying to submit previous transaction

**Questions/Remarks**
- Is it ok to allow another variation if client already has a pending variation application?
- Or notify client that a previous application for variation is in process. Client can apply after *allowed no. of days?

**Comment by mquijom** [comment]
Please comment below the account and case used in this test case.

**Comment by abalita** [comment]
Closing this issue. 
Issue is not applicable to the new variation module.
