### ISSUE TITLE
Minor - Recommend for Compliance in Recent Activity didn't display current task. 

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#49]
Scenario: Current task is Inspection, As per approver case is recommended for Inspection not for compliance but Recent Activity in client portal display recommend for Compliance. 

Credentials:
Username: Vince
Password: Vince123

 - Expected Result
    [ ] Recommend for Inspection

 - Actual Result

![Recommended](https://user-images.githubusercontent.com/34052250/55530603-56765b80-56d9-11e9-8ecc-83840dd09273.PNG)
![Inspection](https://user-images.githubusercontent.com/34052250/55530651-83c30980-56d9-11e9-8cc8-c112b8c2b7a2.PNG)

**Comment by mquijom** [comment]
Deployment Version: **0.1.30**

Modified File(s):
- **fda-client-portal/src/plugins/mixins.js**
- **fda-client-portal/src/components/UserActivity.vue**

Resolution:
The message returns `Recommend for Compliance` always if the action is for the recommendation.
Include the task that is recommended.

![image](https://user-images.githubusercontent.com/34019450/55540832-5c2e6a00-56f6-11e9-89f2-1c2c70753392.png)

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![Inspections](https://user-images.githubusercontent.com/34052250/55611915-872dc200-57b9-11e9-9f82-0e49eddfa72d.PNG)
