### ISSUE TITLE
One email address use in multiple registration

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#50]
Scenario: Register new license multiple times using the same email address ftquiocho@gmail.com

Username: Chz, Chz2, Chz3, Chz4, Chz5

Actual Result:
- Successfully registered 5 new licenses using 1 email address
- 4 limited access, 1 full access

Question/Remarks:
- is this ok?

**Comment by mquijom** [comment]
Relating this issue to #48

**Comment by fqui8** [comment]
Issue re multiple email use in registration fixed.

closing this issue now
