### ISSUE TITLE
MAJOR - Payment Summary missing at first load

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-client-portal#54]
**Scenario: Trying to pay for an application fee**
Username: **mquijom**
Password: **Mark123**
Case No: **l20193103000048**
Application Type: **Renewal**

- Steps to replicate:
1. Login with given user credentials (Must start with this step to show the error)
2. Click Licenses.
3. Search for the given case no with the given application type then click it.
4. Navigate to Payment Summary (Payment Summary will not going to show)
5. Click **Back** button.
6. Search again for the given case no.
7. Navigate to Payment Summary then it will now going to display.

Repeat the steps if you want to show the error.

- Expected Result:
The Payment Summary must display at first load.

- Actual Result:
It didn't display at first load but displays after navigating to it again.

- Browser's console log:
`vue.runtime.esm.js:1887 TypeError: Cannot read property 'fee' of null
    at e.r (PaymentSummary.vue?11ca:1)
    at e.A._render (vue.runtime.esm.js:3535)
    at e.C (vue.runtime.esm.js:4041)
    at oC.get (vue.runtime.esm.js:4444)
    at new oC (vue.runtime.esm.js:4433)
    at Sg (vue.runtime.esm.js:4048)
    at e.hC.$mount (vue.runtime.esm.js:8377)
    at init (vue.runtime.esm.js:3111)
    at a (vue.runtime.esm.js:5943)
    at s (vue.runtime.esm.js:5890)`

![image](https://user-images.githubusercontent.com/34019450/55600944-e6c3a780-5790-11e9-90d4-c592e2798add.png)

**Comment by abalita** [comment]
Closing this issue as the license renewal page is no longer using the old application overview
