### ISSUE TITLE
Documents Upload Error

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#6]
**Issue:** Can't save file to DB in Documents Upload.
-No label or message only PDF file accepted.
-No prompted message if successful uploaded documents or fail.

**Module:** Registration

**Expected Result:**
Can upload and save documents required.
**Actual Result:**
Failed, Can't stored attached file to db.

![fiftyen](https://user-images.githubusercontent.com/34052250/54413481-cb84ef80-4730-11e9-8114-2eb51bbdc90a.PNG)
![nineten](https://user-images.githubusercontent.com/34052250/54413482-cb84ef80-4730-11e9-8820-7f0d3d8c9b19.PNG)

**Comment by mquijom** [comment]
Hi @VPBelo, What account did you use in this test case ?

**Comment by VPBelo** [comment]
username: Chz
password: Chz123

**Comment by mquijom** [comment]
Deployment Version: **0.1.22**

Files: 
- **fda-client-portal/components/Compliance**

Remarks
Uploading module is working fine. But still implemented the message.
***Note: Only PDF files are accepted.**

![image](https://user-images.githubusercontent.com/34019450/54975745-15908f80-4fd3-11e9-9829-914676b1ad92.png)

![image](https://user-images.githubusercontent.com/34019450/54975768-26d99c00-4fd3-11e9-8ed6-aea9c40a6094.png)

![image](https://user-images.githubusercontent.com/34019450/54976816-681f7b00-4fd6-11e9-95b8-9ca59fe3950c.png)

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result

![Compliance](https://user-images.githubusercontent.com/34052250/55054863-2fe27000-509c-11e9-9100-348259601c4c.PNG)
