### ISSUE TITLE
Payment via Credit card from New Registration module

### ISSUE THREAD

**Issue by fqui8** [centralizedinc/fda-client-portal#62]
Account Registered: Chz
PW: Chz123

Scenario: Last step of registration > Payment > Credit Card > Submit
![Screen Shot 2019-04-16 at 10 08 51 AM](https://user-images.githubusercontent.com/36065227/56177450-417ebe00-6031-11e9-90de-d91c1d247bb9.png)

-Actual Result:
Network error, no error or confirmation message, but downloaded receipt
Checked payments in license summary, i accidentally paid 3x. Not aware that payment has been submitted. No error/confirmation/notification
![Screen Shot 2019-04-16 at 10 23 15 AM](https://user-images.githubusercontent.com/36065227/56177647-ef8a6800-6031-11e9-9980-a48c621b4d7a.png)

-Remarks:
must close dialog and notify if payment successfully submitted
client cannot cancel transaction once payment has been submitted

**Comment by abalita** [comment]
closing issue. can't replicate error.
