### ISSUE TITLE
Lack of data get in DB in Mailing Address/Office Address

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#7]
**Issue:** Lack of data get in DB for provinces, cities fields and zip code not working in mailing and office address.
**Module:** New License

**Expected Result:**
Can type/Input client

![j](https://user-images.githubusercontent.com/34052250/54413944-7fd34580-4732-11e9-854e-4cd5138aa807.PNG)
![t](https://user-images.githubusercontent.com/34052250/54413946-806bdc00-4732-11e9-9cd5-7bdd4442eb61.PNG)

**Comment by fqui8** [comment]
@VPBelo 
Fixed. For deployment v.0.1.24

File path: 
/fda-client-portal/src/views/app/licenses/create/tabs/OfficeAddress.vue
/fda-client-portal/src/views/app/licenses/create/tabs/AuthorizedOfficerDetails.vue

Resolved by editing script
![Screen Shot 2019-03-27 at 1 50 35 PM](https://user-images.githubusercontent.com/36065227/55053508-5d78ea80-5097-11e9-86fb-6382e2cfd04a.png)
![Screen Shot 2019-03-27 at 1 50 28 PM](https://user-images.githubusercontent.com/36065227/55053509-5e118100-5097-11e9-811d-6a77596b69c3.png)
![Screen Shot 2019-03-27 at 1 50 19 PM](https://user-images.githubusercontent.com/36065227/55053511-5e118100-5097-11e9-8839-38086f067cb6.png)

**Comment by VPBelo** [comment]
Closing this issue.
