### ISSUE TITLE
My Profile Error

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#9]
**Issue:** Company details must pre filled and User details did not save any changes
**Module**: My Profile

Expected Result:
Can type/Edit client

Actual Result:
Failed, User edit details but did not save any changes.
![lllllll](https://user-images.githubusercontent.com/34052250/54416379-28d16e80-473a-11e9-92dc-02a8c1cac8c4.PNG)

**Comment by fqui8** [comment]
Related to issue #11 , uploading and saving photo avatar

**Comment by mquijom** [comment]
Deployment Version: **0.1.24**

Modified File(s):
- **fda-client-portal/api/UserAPI.js**
- **fda-client-portal/layout/UserLayout.js**
- **fda-client-portal/plugins/mixins.js**
- **fda-client-portal/views/app/Profile.vue**

Resolutions:
Fixed. Only User Accounts available to modify

![image](https://user-images.githubusercontent.com/34019450/55066412-b73ddc80-50b8-11e9-8c02-8275d9c65525.png)

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![profileNew](https://user-images.githubusercontent.com/34052250/55130346-8069d400-5155-11e9-8afb-894fc66c72ec.PNG)

**Comment by VPBelo** [comment]
**Issue:** Unable to change Profile Picture. When the page is reloaded ,the same default image appears.
![profileNew](https://user-images.githubusercontent.com/34052250/55140970-46f49100-5174-11e9-8a11-f47af85338c3.PNG)

**Comment by mquijom** [comment]
Deployment Version: **0.1.25**

Resolution:
Deployment for **0.1.24** didn't reflected to prod

![image](https://user-images.githubusercontent.com/34019450/55199149-fe7cb800-51f3-11e9-838b-2f5799235fc0.png)

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![profileclient](https://user-images.githubusercontent.com/34052250/55202782-ced5ac00-5203-11e9-98b6-4382ffb513ec.PNG)
![profileclient2](https://user-images.githubusercontent.com/34052250/55202783-ced5ac00-5203-11e9-9bef-2667ad21df68.PNG)
